# Generated by Django 4.2.9 on 2024-02-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydegree',
            name='degree',
            field=models.CharField(default='ingenieur', max_length=300),
            preserve_default=False,
        ),
    ]
