# Generated by Django 4.2.9 on 2024-02-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0002_universitydegree_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitydegree',
            name='username',
        ),
        migrations.AddField(
            model_name='universitydegree',
            name='user_uuid',
            field=models.TextField(default=''),
        ),
    ]
