# Generated by Django 4.2.9 on 2024-03-04 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0003_remove_universitydegree_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitydegree',
            name='id_card_photo',
        ),
    ]
