# Generated by Django 4.2.9 on 2024-03-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0004_remove_universitydegree_id_card_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydegree',
            name='did',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
