# Generated by Django 4.2.9 on 2024-03-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0007_universitydegree_bss_universitydegree_jwt'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydegree',
            name='signedvc',
            field=models.TextField(default=''),
        ),
    ]
