# Generated by Django 4.2.9 on 2024-04-20 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0009_universitydegree_ld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitydegree',
            name='did',
        ),
    ]
