# Generated by Django 4.2.9 on 2024-05-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0010_remove_universitydegree_did'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydegree',
            name='zkp_cl',
            field=models.BooleanField(default=False),
        ),
    ]
