# Generated by Django 4.2.9 on 2024-05-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0011_universitydegree_zkp_cl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universitydegree',
            old_name='bss',
            new_name='bbs',
        ),
    ]
