# Generated by Django 4.2.9 on 2024-06-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0012_rename_bss_universitydegree_bbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='universitydegree',
            name='key_uuid',
            field=models.TextField(default=''),
        ),
    ]
