# Generated by Django 4.2.9 on 2024-02-23 17:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.issuer')),
            ],
        ),
    ]
