# Generated by Django 4.2.9 on 2024-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0003_jwtsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwtsignature',
            name='user_uuid',
            field=models.TextField(default=''),
        ),
    ]
