# Generated by Django 4.2.9 on 2024-03-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0004_jwtsignature_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='ec_key_info',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
