# Generated by Django 4.2.9 on 2024-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0005_privatekey_ec_key_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatekey',
            name='key',
            field=models.BinaryField(default=b''),
        ),
    ]
