# Generated by Django 4.2.9 on 2024-03-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0006_privatekey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='key',
            field=models.CharField(default='', max_length=32),
        ),
    ]
