# Generated by Django 4.2.9 on 2024-03-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0007_alter_privatekey_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='key',
            field=models.CharField(max_length=64),
        ),
    ]
