# Generated by Django 4.2.9 on 2024-03-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0008_alter_privatekey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwtsignature',
            name='vc_uuid',
            field=models.TextField(default=''),
        ),
    ]
