# Generated by Django 4.2.9 on 2024-03-26 15:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_issuer_did'),
        ('key_storage', '0009_jwtsignature_vc_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairKeyStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('private_key', models.TextField()),
                ('public_key', models.TextField()),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.issuer')),
            ],
        ),
        migrations.DeleteModel(
            name='PrivateKey',
        ),
    ]
