# Generated by Django 4.2.9 on 2024-04-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0010_pairkeystorage_delete_privatekey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JWTsignature',
        ),
    ]
