# Generated by Django 4.2.9 on 2024-04-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0011_delete_jwtsignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairkeystorage',
            name='key_type',
            field=models.CharField(default='bls'),
        ),
    ]
