# Generated by Django 4.2.9 on 2024-05-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_storage', '0012_pairkeystorage_key_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairkeystorage',
            name='key_type',
            field=models.CharField(default='bls', max_length=10),
        ),
    ]
