# Generated by Django 4.2.9 on 2024-02-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_issuer', models.BooleanField(default=False)),
                ('is_holder', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_issuer', models.BooleanField(default=True)),
                ('is_holder', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=100)),
                ('institution', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
    ]
