# Generated by Django 4.2.9 on 2024-02-25 14:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_issuer_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='holder',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
