# Generated by Django 4.2.9 on 2024-03-04 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_ethdid_holder_did'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holder',
            name='did',
        ),
        migrations.RemoveField(
            model_name='issuer',
            name='did',
        ),
    ]
