# Generated by Django 4.2.9 on 2024-03-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_holder_did_alter_issuer_did'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuer',
            name='did',
            field=models.CharField(default='', max_length=255),
        ),
    ]
