# Generated by Django 4.2.9 on 2024-03-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sessionnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionnumber',
            name='used_for_signing',
            field=models.BooleanField(default=False),
        ),
    ]
